### ISSUE TITLE
220V dont works

### ISSUE THREAD

**Issue by shalom198** [DudeYarvie/JARViE_Home_Automation_Modem#3]
the module works fine with 110V but dosnt works with 220V 
what wrong ??

**Comment by DudeYarvie** [comment]
Shalom198 and I are discussing this via e-mail.  We'll update the thread in a clean way that shows issue + solution once complete.  Now I'm trying to understand his setup since I can't physically see it.  I'm also working on setting up a 220VAC PLM master and slave test to verify that communications are still successful at 220VAC.

**Comment by DudeYarvie** [comment]
Shalom,

I understand you're using 220VAC @ 50 Hz source.  Please provide pictures or diagrams to describe the setup to me in **detail**.  I need know all the components involved and how they are interconnected.  I have no idea what your setup looks like, I need this info in order to troubleshoot it and provide a solution.

-Jarvis

**Comment by xfbs** [comment]
If you need someone else to test it out on a 230V power line, I am hereby volunteering.

**Comment by shalom198** [comment]
Hi
Thank you very much for the desire I very much appreciate it
My situation today is that on the power line of the 220V there is no
communication
I got a scoop device, and found that there is noise in the line (I measured
at the point of the TX) even when the TDA does not transmit, the noise is
about KHZ 70-90, 200-300MV
There seems to be some resonance
I do not know how to use the scoop device professionally, I thought to
measure the power line itself to see if the noise is in the power line
regardless of the PLC or the PLC creates it
But I do not know how to measure the power line using the scoop device, I
am afraid to burn it

‫בתאריך יום ג׳, 20 ביולי 2021 ב-1:57 מאת ‪Patrick Elsen‬‏ <‪
***@***.***‬‏>:‬

**Comment by shalom198** [comment]
Hello again
I discovered something interesting, I replaced the serial capacitor at the
entrance (C10)
Instead of 47NF I put 470NF (I saw that this is the value in the APLICATION
NOTE)
I replaced only one module, and then an interesting thing happened, the
second module read the communication correctly, however when I also
replaced the capacitor in the second module, again there was a complete
lack of communication

‫בתאריך יום ג׳, 20 ביולי 2021 ב-23:00 מאת ‪SH JO‬‏ ***@***.***
‬‏>:‬

**Comment by DudeYarvie** [comment]
Shalom,

Restore the demo/breakout boards with the original 47nF CAP and swap out XTAL, X1, with a 7.3728 MHz 18pF standard crystal like [MPN: ABL-7.3728MHZ-B2](https://www.mouser.com/ProductDetail/ABRACON/ABL-73728MHZ-B2?qs=H8AWquzS%2FlMl5W3SEVtd2Q%3D%3D).  This adjusts the PLM carrier frequency to 115kHz which matches the resonant frequency of the tuning circuitry.   I strongly believe the boards I sent you have an 8MHz crystal which sets the PLM carrier frequency to 125kHz.  

-Jarvis

**Comment by shalom198** [comment]
hi, thanks alot, i try right now

‫בתאריך יום ו׳, 14 בינו׳ 2022 ב-0:45 מאת ‪Jarvis Hill‬‏ <‪
***@***.***‬‏>:‬

**Comment by shalom198** [comment]
, I switched to 7.3728 MHz, but it did not work , the same problem.
Currently the system only works if I put an autotransformer (220V > 110V )
between the  mains  of electricity
and the line on which I put the POWERLINE

Thank you very much for everything, hoping we can find a solution

‫בתאריך יום ו׳, 14 בינו׳ 2022 ב-9:28 מאת ‪SH JO‬‏ ***@***.***‬‏>:‬

**Comment by DudeYarvie** [comment]
Ok well thanks for trying it.

**Comment by shalom198** [comment]
Attached are my attempts

‫בתאריך יום ב׳, 17 בינו׳ 2022 ב-22:48 מאת ‪Jarvis Hill‬‏ <‪
***@***.***‬‏>:‬
