### ISSUE TITLE
Arduino IDE Issues Related to ATmega Core, Bootloader, & Fuse Settings

### ISSUE THREAD

**Issue by Intechgreater** [DudeYarvie/JARViE_Home_Automation_Modem#6]
In the process of loading a first example sketch I discovered my demo boards have a slightly different MCU model (ATmega328 instead of ATmega328**P** in the docs). I understand they're essentially the same with the P version being a lower power option and should be programmable with the same settings. However, their device signatures being different prevented sketch upload. Since I'm not well versed in this aspect of Arduino and didn't realized at the time I could have just overridden the signature check I ended up just overwriting the preprogrammed bootloader and fuse settings with [MCUdude's MiniCore](https://github.com/MCUdude/MiniCore).
Here are my Arduino IDE menu fuse settings, with an UNO configured to be an ISP:
![image](https://user-images.githubusercontent.com/10334392/227789328-9afa2690-3980-4107-9b45-329333e27021.png)
So this setup works but only for the first sketch upload. For each new upload I have to reburn the bootloader to get it to upload, otherwise I get these errors:
[Upload Errors.txt](https://github.com/DudeYarvie/JARViE_Home_Automation_Modem/files/11072228/Upload.Errors.txt)
I see the fuse settings provided here [Firmware/src/Shahara/Shahara_ATmega328p_MCU_FUSE_Settings.txt](Firmware/src/Shahara/Shahara_ATmega328p_MCU_FUSE_Settings.txt) but not sure how to program them yet. One thing I question though is `EXTXOSC_8MHZ` in `SUT_CKSEL = EXTXOSC_8MHZ_XX_16KCK_14CK_65MS`. I would it expect to be `EXTXOSC_16MHZ` to match the external 16MHZ crystal.
Thoughts?

**Comment by DudeYarvie** [comment]
OK so you’re trying to update code on the PLM Shahara’s ATmega328 using the Arduino IDE, correct? What programmer are you using? 

I use the Atmel Studio IDE and an AVR ISP Mk2 programmer to update the fuse settings and to flash/update the firmware.  Here's some instructions on how I program the Shahara,
https://github.com/DudeYarvie/JARViE_Home_Automation_Modem/blob/master/Firmware/src/Shahara/Programming%20the%20PLM%20Shahara%20CCA%20using%20Atmel%20Studio.pdf

It’d be nice to know how to update the firmware/code via the Arduino IDE more smoothly than what you’re experiencing. Thanks for logging the issue.

**Comment by Intechgreater** [comment]
Yes, currently in Arduino IDE 1.8.16
Using an UNO R3 running ArduinoISP as the programmer, connected via the ICSP header to Shahara, but with the Reset signal coming from UNO pin 10. And a 10uF cap between GND and RESET on the UNO.

**Comment by Intechgreater** [comment]
I now see thorough instructions on how to program via Atmel Studio v7.0.2389 were uploaded. Thanks! 
In the meantime I installed the current version now called Microchip Studio v7.0.2594 (twice) but it gives me an exception error when trying to open Tools -> Device Programming, and when trying to create a new project!
Will try your approach next...
Also noticed the new Arduino IDE version 2.0.4 and installed it. The errors with subsequent sketch uploads went away. BUT there's another issue in this and previous version: in PLM_Shahara_Master_Transmit_Handshaking_1.0 (and slave version) the line `msgBuffer[MAX_BUF_SIZE]="";` produces the error `invalid conversion from 'const char*' to 'char' [-fpermissive]`
If I replace `""` with `'\0'` it will compile but does that still accomplish the same thing, or what do you suggest?

**Comment by Intechgreater** [comment]
Dang, still getting the same errors in Atmel Studio as I did in Microchip Studio. From the research I've done so far it may have something to do with Microsoft Visual Studio?

1. Tools -> Device Programming:

> Provide value on 'System.Windows.Baml2006.TypeConverterMakupExtension' threw an exception.

![Atmel Studio 7 0 - Tools - Device Programming Error - Screenshot 2023-03-26 174010](https://user-images.githubusercontent.com/10334392/227846714-889ce201-886c-474f-9f0f-f3b48f9ed5ad.png)

2. File -> New -> File or Project:

> Failed to create a 'ImageSource' from text'..\Images\Medium.png'.

![Atmel Studio 7 0 New Project Error - Screenshot 2023-03-27 005521](https://user-images.githubusercontent.com/10334392/227846960-48d3ab4c-3f9a-47df-97eb-4ef12c770030.png)

**Comment by Intechgreater** [comment]
Was able to get Atmel Studio installed on a different PC and Device Programming to come up. Will take it further next chance I get...

**Comment by Intechgreater** [comment]
The High Fuse value in the programming instructions corresponds to EESAVE and BOOTSZ settings different than those in Shahara_ATmega328p_MCU_FUSE_Settings.txt
Which should it be?
![ATmega328 Fuses Atmel Studio Screenshot Marked](https://user-images.githubusercontent.com/10334392/228126470-8054e468-ca11-47e4-885f-b3fc49cb2771.png)

**Comment by DudeYarvie** [comment]
I see the following settings in the Shahara_ATmega328p_MCU_FUSE_Settings.txt. 
_FUSE Registers,
-> EXTENDED = 0xFD (valid)
-> HIGH = 0xDE (valid)
-> LOW = 0xFF (valid)_

This match the settings the programming document provides.  Are you saying there's a difference between settings provided in the fuse setting and programming documents?

**Comment by Intechgreater** [comment]
It's the settings below the fuse register lines in the txt doc, pasted below. I see how the programming doc alone provides the necessary info to program the correct settings though.

> FUSE Names,
> -> **BODLEVEL = 2V				//Brownout detector trigger level**
> -> RSTDISBL = [ ]				//Reset disabled		
> -> DWEN = [ ]					//Debug wire enabled
> -> SPIEN = [X]					//Serial programming download (SPI) enabled
> -> WDTON = [ ]					//Watchdog timer always on
> -> **EESAVE = [X]					//Preserve EEPROM through the chip erase cycle**	
> -> **BOOTSZ = 2048W_3800				//Select boot size**
> -> BOOTRST = [X]				//Boot reset vector enabled
> -> CKDIV8 = [ ]					//Divide clock by 8 internally
> -> CKOUT = [ ]					//CLK output on PORTB0
> -> SUT_CKSEL = EXTXOSC_8MHZ_XX_16KCK_14CK_65MS	//CLK select

**Comment by Intechgreater** [comment]
While waiting for a real programmer compatible with Atmel Studio to arrive, I was able to learn how to read/set the fuse registers and upload the binaries you provided via command line using avrdude. Intimidating at first knowing about the risks but relatively easy once acquainted, and satisfying!
Per your suggestion for testing, the master and slave handshake examples each on a Shahara connected together via J1 (no AC power yet), and getting 5V from an UNO, works!
5 fast LED blinks on master -> slave LED on -> 8 slow LED blinks on master -> 5 fast blinks on master -> slave LED off -> 8 slow LED blinks on master, repeat...
However, when the system is connected to 12VAC (converted to 5VDC for circuit power on each Shahara), the master just cycles through the 5 fast blinks with nothing from the slave. I'll have to take a closer look with a scope next time to see what's going on at the optocoupler. I paralleled a 1.5K ohm resistor with R6 to source enough current on 12VAC. Thoughts? If more help is needed I can start a new thread.

**Comment by DudeYarvie** [comment]
Opened a separate  for the post above.  

In regards to, what are the correct fuse settings?  The correct fuse settings are below.  I will correct the fuse name settings provided in [Update Shahara_ATmega328p_MCU_FUSE_Settings.txt](https://github.com/DudeYarvie/JARViE_Home_Automation_Modem/commit/b0735e7ec43ef29e897dd35bf4958611dc099d51)

EXTENDED = 0xFD (valid)
HIGH = 0xDE (valid)
LOW = 0xFF (valid)

Fuse Names, 
BODLEVEL = 2V7
RSTDISBL = [ ]
DWEN = [ ]
SPIEN = [X]
WDTON = [ ]
EESAVE = [ ]
BOOTSZ = 256W_3F00
BOOTRST = [X]
CKDIV8 = [ ]
CKOUT = [ ]
SUT_CKSEL = EXTXOSC_8MHZ_XX_16KCK_14CK_65MS

**Comment by DudeYarvie** [comment]
I deleted your comment above and opened a new issue.

In regards to, what are the correct fuse settings?  The correct settings are below.  I corrected the "Fuse Names" section of [Update Shahara_ATmega328p_MCU_FUSE_Settings.txt](https://github.com/DudeYarvie/JARViE_Home_Automation_Modem/commit/b0735e7ec43ef29e897dd35bf4958611dc099d51)

EXTENDED = 0xFD (valid)
HIGH = 0xDE (valid)
LOW = 0xFF (valid)

Fuse Names,
BODLEVEL = 2V7
RSTDISBL = [ ]
DWEN = [ ]
SPIEN = [X]
WDTON = [ ]
EESAVE = [ ]
BOOTSZ = 256W_3F00
BOOTRST = [X]
CKDIV8 = [ ]
CKOUT = [ ]
SUT_CKSEL = EXTXOSC_8MHZ_XX_16KCK_14CK_65MS

**Comment by DudeYarvie** [comment]
@Intechgreater is this still an open issue or did we get the fuse settings sorted out?

**Comment by Intechgreater** [comment]
The fuse settings are resolved. Thanks!
