### ISSUE TITLE
Unsuccessful communications with 12VAC powerline generated from a transformer

### ISSUE THREAD

**Issue by DudeYarvie** [DudeYarvie/JARViE_Home_Automation_Modem#8]
While waiting for a real programmer compatible with Atmel Studio to arrive, I was able to learn how to read/set the fuse registers and upload the binaries you provided via command line using avrdude. Intimidating at first knowing about the risks but relatively easy once acquainted, and satisfying!
Per your suggestion for testing, the master and slave handshake examples each on a Shahara connected together via J1 (no AC power yet), and getting 5V from an UNO, works!
5 fast LED blinks on master -> slave LED on -> 8 slow LED blinks on master -> 5 fast blinks on master -> slave LED off -> 8 slow LED blinks on master, repeat...
However, when the system is connected to 12VAC from a magnetic transformer (converted to 5VDC for circuit power on each Shahara), the master just cycles through the 5 fast blinks with nothing from the slave. I'll have to take a closer look with a scope next time to see what's going on at the optocoupler. I paralleled a 1.5K ohm resistor with R6 to source enough current on 12VAC. Thoughts? If more help is needed we can start a new thread.

_Originally posted by @Intechgreater in https://github.com/DudeYarvie/JARViE_Home_Automation_Modem/issues/6#issuecomment-1487980106_

**Comment by Intechgreater** [comment]
Based on your zero cross reference with pulses ~2ms wide, I'm guessing my ~680µs pulses are too short? Which means I need a higher input/lower resistance feeding the optocoupler for the LEDs to turn on sooner & stay on longer?

![Zero_Cross_Detection_Capture_Annotate1](https://user-images.githubusercontent.com/10334392/229037439-14d2f336-ed69-4baa-ade5-285d49ea594f.PNG)

**Optocoupler Input - Cycle**
![Optocoupler Input - Cycle](https://user-images.githubusercontent.com/10334392/229036165-d149bfd9-179a-4b5a-9f74-657d62f5cb5c.png)

**Optocoupler Input - Pulse**
![Optocoupler Input - Pulse](https://user-images.githubusercontent.com/10334392/229036366-39261460-3999-4915-92b8-e7f8bbcf6c4d.png)

**MCU INT Pin - Cycle**
![MCU INT Pin - CYcle](https://user-images.githubusercontent.com/10334392/229036687-bab55640-668a-47e8-9cab-84bed4bfe3ee.png)

**MCU INT Pin - Pulse**
![MCU INT Pin - Pulse](https://user-images.githubusercontent.com/10334392/229036749-5c6d5144-73e0-4402-9fb4-49408074af67.png)

**Comment by DudeYarvie** [comment]
@Intechgreater could you supply a block diagram/sketch of the setup showing all components?  The fact that the master cycles through the 5 fast blinks with nothing from the slave makes me think it's not a zero-cross detection issue.  First, comment out the zero-cross detection lines of master handshaking code and see if communications is successful.

      //Wait for AC mains zero cross point
      while(1){
        ZERO_CROSS_FLAG = digitalRead(2);                 // read the input pin
        if (ZERO_CROSS_FLAG == 1) break;
      }

**Comment by Intechgreater** [comment]
Can do. In the meantime I'll share some scope screenshots taken last night. I see how my ~600µs logic high pulses on the INT pin are a fraction of the ~2ms pulses in your reference screenshot. Guessing the input to the optocoupler is too high resulting in the INT pin being pulled low for too much of a cycle?

**Reference zero cross circuit output:**
![Zero_Cross_Detection_Capture_Annotate1](https://user-images.githubusercontent.com/10334392/229127073-973ac65f-4e6c-4969-ade2-faafdafb3e65.PNG)

**Optocoupler Input - Cycle** (measured between pins 1 & 2 on optocoupler)
![Optocoupler Input - Cycle](https://user-images.githubusercontent.com/10334392/229125094-27f3bf4c-d53b-4888-ae12-da25e0e398be.png)

**Optocoupler Input - Pulse**
![Optocoupler Input - Pulse](https://user-images.githubusercontent.com/10334392/229125202-ef0aaf3c-552c-4862-85e4-edc13a94da60.png)

**Optocoupler Input - Pulse Transition**
![Optocoupler Input - Pulse Transition](https://user-images.githubusercontent.com/10334392/229125276-4b6b8351-8c44-48d4-9f53-d0fabea64806.png)

**MCU INT Pin - Cycle**
![MCU INT Pin - CYcle](https://user-images.githubusercontent.com/10334392/229125374-16f3f2a7-e69a-410c-a1fd-cb40ee63b8a6.png)

**MCU INT Pin - Pulse** (measuring portion Atmega328 considers logic high)
![MCU INT Pin - Pulse](https://user-images.githubusercontent.com/10334392/229125479-12b467e1-64c4-48e2-8e28-a644a7f604f6.png)

**MCU INT Pin - Pulse Gap**
![MCU INT Pin - Pulse Gap](https://user-images.githubusercontent.com/10334392/229125587-ed53e0ff-a1eb-48b8-b500-051015d5b44c.png)

**Comment by DudeYarvie** [comment]
From the _Optocoupler Input - Pulse_ plot I understand that the pulse-width/on-time of the zero-cross detection is active for ~8.1ms when a zero crossing event occurs but from the _MCU INT Pin - Pulse (measuring portion Atmega328 considers logic high)_ the zero-cross INT signal to the MCU is only 680us wide.  For starters, I'd place a lower resistance value and drive more current into the optocoupler to quickly see if INT signal PW approaches the optocoupler input signal PW.  

It already seems like you're supplying enough drive current to the optocoupler though.  Double-check my math.  With a 1.5k placed in parallel with R6 and a 15VAC source, I calculate that you're driving a peak current and RMS current of,

**1.5k || R6** = 1489.8 Ohms
**Irms** = (15VAC-1.2Vdiode)/1489 = 9 mArms
**Ipeak** = (Vpeak-1.2Vdiode)/1.5k =[ ([(15VAC*2.8284)/2]) - 1.2Vdiode]*1.5e3 = 13.3 mApeak

**Comment by Intechgreater** [comment]
Thanks for the feedback.

Did some more probing and swapping elements out. Looks like the module I'm converting 12-15VAC to 5VDC with to power the boards is distorting the modem signals too much somehow? The module is a small constant-current LED driver modified by having a 5V regulator connected to the converted/protected power & ground traces on the driver board.

For simplified troubleshooting, I removed the modified LED driver modules from the the Shahara boards and connected a non-modified, slightly different model LED driver/light to the output of the transformer and switched Shahara board power over to an UNO plugged into a 120VAC USB power supply:
![Jarvie 12VAC PLC Troubleshooting Setup A](https://user-images.githubusercontent.com/10334392/229364137-c0c5f664-748e-4d8b-bb7d-d492c4c511fa.png)
In the following screenshots, CH1 = Tx and CH2 = Rx at the modem on the Slave board. The master board is running the handshake code with the zero-cross detection lines commented out.

**Transformer OFF, Comm Good:**
![SlaveTxRx1a](https://user-images.githubusercontent.com/10334392/229313993-d23dac7c-38c1-4691-8dec-18b0b334a94c.png)

**Transformer OFF, zoomed in:**
![SlaveTxRx1b](https://user-images.githubusercontent.com/10334392/229314004-ca3c9205-7335-45f4-84bc-59440cc2436f.png)

**Transformer ON,  Comm Good:**
![SlaveTxRx2a](https://user-images.githubusercontent.com/10334392/229314278-d20e30cb-c793-4fe4-b8d6-e8a176d0349e.png)

**Transformer ON, zoomed in:**
![SlaveTxRx2b](https://user-images.githubusercontent.com/10334392/229314282-a0345bde-f0ed-4a03-b180-40bab93df60f.png)

**Transformer ON with LED driver/light connected to transformer output (along with boards, all in parallel).  Comm BAD (no response from Slave)**
![SlaveTxRx3a](https://user-images.githubusercontent.com/10334392/229314305-8230f318-dea3-4dfd-835d-526d46f38620.png)

**Transformer ON with LED driver connected, zoomed in**
![SlaveTxRx3b](https://user-images.githubusercontent.com/10334392/229314331-5a4f7178-0446-4c7e-bc64-cd07ce910586.png)

**Comment by DudeYarvie** [comment]
Thanks for the system diagram.  I agree, the LED driver is what's causing comm issues.  It appears that it's distorting the PLM comm signal because it's loading it.  I'd attempt to make the LED driver input appear invisible to the PLM comms.  Said another way, make the LED driver input impedance as high as possible at the PLM comm frequency.   It does seem like the LED driver has some AC line filtering on the front-end but try adding a common-mode choke/AC line filter in series between the CC Triple LED Driver and the transformer connection.  I'm not sure what the power requirements are for the LED driver but I suggest one of the choke/AC line filters from the KEMET 21NVS-M/NHS-M series.  To solve issues like these I've used MPN: SSR21NVS-M12220, which is a 22mH,1.2A DCR=0.35mOhms choke.   The KEMET series offers a good amount of options.  How I went about selecting one was, first I needed to pick a choke with low DCR and one that could handle the current needed.  In this case, the max current required by the LED driver.  Then, I went to the _Frequency Requirements_ section of the 21NVS-M/NHS-M series datasheet and looked at the impedance that choke would provide at the PLM comm frequency (e.x. 125 kHz).  The SSR21NVS-M12220 choke appears as ~20 kOhm @ 125 kHz.  Other chokes present higher impedances at this frequency but may have a lower current rating.  Look at the KEMET datasheet and pick one that can support the max LED driver current.

**Comment by Intechgreater** [comment]
I appreciate the explanation and suggestion - ordering a few of those options to test.  It's nice how it's a single component addition. For later modifications to reduce the size of the overall setup, I wonder if there are other approaches to change the driver impedance at comm frequencies, that take up less space (but maybe require more components), and/or a matter of changing driver component values?

**Comment by DudeYarvie** [comment]
@Intechgreater I'm sure there's physically smaller chokes that could be used but the one I suggested has been proven to solve issues like this in the past.  If it solves the problem, then let's look into a smaller choke.  Did you ever order and insert the suggested chokes between the CC Triple LED Driver and the 12VAC power line connection to see if this fixed the comm issue while the LED driver is terminated to the power line?

**Comment by Intechgreater** [comment]
The chokes fixed the issue! I meant to provide an update back when I tried it but ended up having to pause the entire project for a while since priorities shifted. I'm planning to get back to it for further refinement...

**Comment by DudeYarvie** [comment]
Cool. Thanks for the update. Closing this issue.
